---
- name: Make sure the redmine db is exists
  postgresql_db:
    login_host: "{{ host }}"
    login_user: "{{ redmine_db_psql_super_user }}"
    login_password: "{{ redmine_db_psql_super_password }}"
    name: "{{ database }}"
    encoding: "{{ encoding }}"

- name: Make sure the redmine user is exists
  postgresql_user:
    login_host: "{{ host }}"
    login_user: "{{ redmine_db_psql_super_user }}"
    login_password: "{{ redmine_db_psql_super_password }}"
    db: "{{ database }}"
    name: "{{ username }}"
    password: "{{ password }}"
